# Generated by Django 5.2.7 on 2025-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_is_online_profile_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresslog',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Progress Logs'},
        ),
        migrations.AddField(
            model_name='progresslog',
            name='activity_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('lesson', 'Lesson'), ('practice', 'Speaking Practice'), ('vocab', 'Vocabulary'), ('grammar', 'Grammar'), ('other', 'Other')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent')], default='beginner', max_length=20),
        ),
    ]
